# fly.toml app configuration file generated for demo-sor on 2024-11-03T17:31:12-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'demo-sor'
primary_region = 'gru'

[build]
  dockerfile = 'src/main/docker/Dockerfile.native'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
